---
title: "Data import"
output: github_document
---

This file is for doing data import

```{r}
library(tidyverse)
library(haven)
```

Import first dataset

```{r}
litters_df = 
  read_csv(
    file = "data_import_examples/FAS_litters.csv",
    na = c("", "NA", ".")
  )

litters_df = janitor::clean_names(litters_df)
```

Import second dataset

```{r}
pups_df = 
  read_csv(
    file = "data_import_examples/FAS_pups.csv", 
    skip = 3,
    na = c("", "NA", ".")
  )
## doing all NA cleaning during the import step, keep everything fix and clean
pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or tail
```{r}
head(litters_df, 6)

tail(pups_df, 5)
```

Skimming??
```{r}
skimr::skim(pups_df)
```


## Import excel

```{r}
library(tidyverse)
library(readxl)
```

```{r}
mlb_df = read_excel("data_import_examples/mlb11.xlsx")
```

look at the data
```{r}
mlb_df
```

load LotR words
```{r}
fotr_df = 
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "B3:D6"
  )
```

What about two
```{r}
tt_df = 
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "F3:H6"
  )
```

## Import SAS

Read in the PULSE dataset

```{r}
pulse_df = 
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

